Deprecation warning fix
arturtamborski/notion-py pull request #58
Opened 2020-10-04 15:37 UTC by ArtemErmulin

Deprecated since version 3.3, will be removed in version 3.9:
Moved Collections Abstract Base Classes to the
`collections.abc` module.

For more, see: https://docs.python.org/3.7/library/collections.html

2020-10-04 20:29 UTC, arturtamborski requested changes
Hi! Thanks for taking care of the warnings :)
I left one suggestion and a comment explaining it, please take a look.

2020-10-04 20:29 UTC, arturtamborski commented on notion/store.py
> +from collections.abc import Callable
```suggestion
from typing import Callable
```

That's what I meant originally. I've imported `Callable` from `collections` by mistake.

2020-10-05 07:38 UTC, ArtemErmulin commented on notion/store.py
> +from collections.abc import Callable
Yep, sure:)

2020-10-05 07:47 UTC, arturtamborski approved these changes

2020-10-05 07:47 UTC, merged